### ISSUE TITLE
Error executing jar file

### ISSUE THREAD

**Issue by sachinmalepati** [dbpedia/list-extractor#4] opened 2018-02-15 16:20 UTC
Hi,
  I am facing an issue when i run list extractor project in my mac. When I ran the command "python listExtractor.py s William_Gibson en" I got the following error

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/machinelinking/main/JSONpediaException
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3139)
	at java.base/java.lang.Class.getMethodsRecursive(Class.java:3280)
	at java.base/java.lang.Class.getMethod0(Class.java:3266)
	at java.base/java.lang.Class.getMethod(Class.java:2063)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:57)
Caused by: java.lang.ClassNotFoundException: com.machinelinking.main.JSONpediaException
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 6 more
```
I think the main problem is in execution of the jsonpedia_wrapper.jar
I am running it on macOS 10.13.2 and java version is 9.0.1
I tried googling the issue but didn't get any satisfactory results (I tried setting classpath to the jar location).
Please help!

**Comment by krishh-konar** [comment] 2018-02-19 09:56
Hi, I haven't tested it on Mac. Give me some time, I'll look into it.

**Comment by krishh-konar** [comment] 2018-02-20 06:01
Meanwhile, you can use the older version of `jsonpedia_convert()`, `find_page_redirects()` which use the web-api calls instead of using the Jsonpedia wrapper. That should work for now.

**Comment by krishh-konar** [comment] 2018-05-10 14:23
As discussed, the problem is with the Java version. This works fine with Java version 8.
Need to make some changes and re-compile the whole package in order to support for Java 9.
Closing this issue.

**Closed as completed by krishh-konar** 2018-05-10 14:23 UTC
